name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  instrumentation-tests:
    name: Instrumentation tests
    runs-on: macos-latest
    strategy:
      fail-fast: true
      matrix:
        api-level: [ 23, 25, 29 ]
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "${{ secrets.SECRET_PROPERTIES }}" > secret.properties.asc
          gpg -d --passphrase "${{ secrets.SECRET_PROPERTIES_PASSPHRASE }}" --batch secret.properties.asc > secret.properties

      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/build.gradle.kts') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/src/Dependencies.kt') }}

      - name: Instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          profile: Nexus 6P
          script: ./gradlew connectedCheck
